const projectData = [
    {
        id: 1,
        projectTitle: 'estyle',
        description: '',
        date: '',
        tools: ['reactJs', 'Figma', 'Bootsrap', 'Git'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 2,
        projectTitle: 'ehub',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'Bootstrap', 'Git'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'right',
    },
    {
        id: 3,
        projectTitle: 'ace',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'Bootstrap', 'Git'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 4,
        projectTitle: 'fuelflow',
        description: '',
        date: '',
        tools: ['reactJS', 'laravel', 'php', 'mysql'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'right',
    },
    {
        id: 5,
        projectTitle: 'sweatmucle',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'materialUI'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 6,
        projectTitle: 'portfolio',
        description: '',
        date: '',
        tools: ['reactJS'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'right',
    },
]

export default projectData;