const projectData = [
    {
        id: 1,
        projectTitle: 'estyle',
        description: '',
        date: '',
        tools: ['reactJs', 'Figma', 'Bootsrap', 'Git'],
        projectLink: 'https://estyle.vercel.app/',
        githubLink: 'https://github.com/Christiannaira/estyleproject.git',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 2,
        projectTitle: 'ehub',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'Bootstrap', 'Git'],
        projectLink: 'https://mini-project2-react.vercel.app/',
        githubLink: 'https://github.com/Christiannaira/ehubproject.git',
        projectImg: '',
        color: '',
        animation: 'right',
    },
    {
        id: 3,
        projectTitle: 'ace',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'Bootstrap', 'Git'],
        projectLink: 'https://aceproject.vercel.app/',
        githubLink: 'https://github.com/Christiannaira/aceproject.git',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 4,
        projectTitle: 'fuelflow',
        description: '',
        date: '',
        tools: ['reactJS', 'laravel', 'php', 'mysql'],
        projectLink: '',
        githubLink: '',
        projectImg: '',
        color: '',
        animation: 'right',
    },
    {
        id: 5,
        projectTitle: 'sweatmucle',
        description: '',
        date: '',
        tools: ['restAPI', 'reactJS', 'materialUI'],
        projectLink: 'https://sweatmuscle.vercel.app/',
        githubLink: 'https://github.com/Christiannaira/sweatmuscle.git',
        projectImg: '',
        color: '',
        animation: 'left',
    },
    {
        id: 6,
        projectTitle: 'portfolio',
        description: '',
        date: '',
        tools: ['reactJS'],
        projectLink: 'https://sampleportfolio-gules.vercel.app/',
        githubLink: 'https://github.com/Christiannaira/portfolioproject01.git',
        projectImg: '',
        color: '',
        animation: 'right',
    },
]

export default projectData;